template:
  type: http
  url: "{{stack_group_config.aws_infra_templates_root_url}}/v0.3.0/templates/VPC/vpc-20-private.yaml"
stack_name: airflow-vpc-test

parameters:
  VpcName: airflow-vpc-test
  VpcSubnetPrefix: "172.22"

stack_tags: {{stack_group_config.default_stack_tags}}
